-- MySQL Script generated by MySQL Workbench
-- Mon Dec 13 00:58:50 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema pollution
-- -----------------------------------------------------
CREATE DATABASE IF NOT EXISTS `pollution-db` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
USE `pollution-db`;
-- -----------------------------------------------------
-- Table `stations`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `stations` ;

CREATE TABLE IF NOT EXISTS `stations` (
  `station_id` INT NOT NULL,
  `location` VARCHAR(45) NULL,
  `geo_point_2d` VARCHAR(45) NULL,
  PRIMARY KEY (`station_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `readings`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `readings` ;

CREATE TABLE IF NOT EXISTS `readings` (
  `reading_id` INT NOT NULL,
  `datetime` DATETIME NULL,
  `nox` FLOAT NULL,
  `no2` FLOAT NULL,
  `no` FLOAT NULL,
  `pm_10` FLOAT NULL,
  `nvpm_10` FLOAT NULL,
  `vpm_10` FLOAT NULL,
  `nvpm_2.5` FLOAT NULL,
  `pm_2.5` FLOAT NULL,
  `vpm_2.5` FLOAT NULL,
  `co` FLOAT NULL,
  `o3` FLOAT NULL,
  `so2` FLOAT NULL,
  `temperature` REAL NULL,
  `rh` INT NULL,
  `airpressure` INT NULL,
  `date_start` DATETIME NULL,
  `date_end` DATETIME NULL,
  `current` TEXT(5) NULL,
  `instrument_type` VARCHAR(32) NULL,
  `readingscol` VARCHAR(45) NULL,
  `stations_id-fk` INT NOT NULL,
  PRIMARY KEY (`reading_id`),
  INDEX `fk_readings_stations_idx` (`stations_id-fk` ASC) VISIBLE,
  CONSTRAINT `fk_readings_stations`
    FOREIGN KEY (`stations_id-fk`)
    REFERENCES `stations` (`station_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `schema`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `schema` ;

CREATE TABLE IF NOT EXISTS `schema` (
  `measure` VARCHAR(32) NOT NULL,
  `description` VARCHAR(64) NULL,
  `unit` VARCHAR(24) NULL,
  PRIMARY KEY (`measure`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
